runMode=Multiple
client.1.name=Sarvagram
client.1.url=https://collections.sarvagram.com/#/signin
client.1.username=pradeep.r@sen-sei.in
client.1.password=0hiM9lxGiWcuiQNk
client.1.sso=true

client.2.name=Conatus
client.2.url=https://encorepay.conatus.co.in/#/signin
client.2.username=jobview
client.2.password=Admin@123
client.2.sso=false

client.3.name=Prayaan Capital
client.3.url=https://encollect.prayaancapital.net/collectionsclient/#/signin
client.3.username=jobview
client.3.password=Admin@123
client.3.sso=false

client.4.name=Purple Finance
client.4.url=https://encorepay.purplefinance.in/encore-pay/#/signin
client.4.username=jobview
client.4.password=Admin@123
client.4.sso=false

client.5.name=Alpha Rupee
client.5.url=https://encorepay.alpharupee.in/pay/#/signin
client.5.username=senseiadmin
client.5.password=Admin@123
client.5.sso=false


client.6.name=Samunnati
client.6.url=https://samcollect.samunnati.com/#/signin
client.6.username=jobview
client.6.password=Admin@123
client.6.sso=false

client.7.name=Samasta
client.7.url=https://encoreprod.iiflsamasta.com/encore-pay/#/signin
client.7.username=jobview
client.7.password=Admin@123
client.7.sso=false

client.8.name=Lakshmithra
client.8.url=https://encoreprod.lakshmithra.com/encore-pay/#/signin
client.8.username=jobview
client.8.password=Admin@123
client.8.sso=false

client.9.name=Altum
client.9.url=https://encorepay-collect.achfpl.com/#/signin
client.9.username=jobview
client.9.password=Admin@123
client.9.sso=false


browser=chrome
headless=true
implicitWait=0
explicitWait=20
pageLoadTimeout=45
reportEmailTo=
reportEmailCc=
smtpHost=smtp.gmail.com
smtpPort=587
smtpUsername=
smtpPassword=
googleChatWebhookUrl=https://chat.googleapis.com/v1/spaces/AAQAo_LZao8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=hdWDDnrdms7kzw8JmIKktQMwPPbexSZWILbWdHEpBt0
